version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: "org.opensearch:opensearch"
        versions: [">=2.3.0"] # Prevent updates to version 2.3.0 or higher due to potential breaking changes. See: https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.3.0.md
      - dependency-name: "org.opensearch.client:opensearch-rest-high-level-client"
        versions: [">=2.3.0"] # Prevent updates to version 2.3.0 or higher due to potential breaking changes. See: https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.3.0.md
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: "org.opensearch:opensearch"
        versions: [">=2.3.0"] # Prevent updates to version 2.3.0 or higher due to potential breaking changes. See: https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.3.0.md
      - dependency-name: "org.opensearch.client:opensearch-rest-high-level-client"
        versions: [">=2.3.0"] # Prevent updates to version 2.3.0 or higher due to potential breaking changes. See: https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.3.0.md
    groups:
      dependencies:
        patterns:
          - "*"
    target-branch: master