version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:17"
      timezone: "Etc/GMT+7"
    groups:
      dependencies:
        patterns:
          - "*"
    target-branch: "dependabot-test"