version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.opensearch*"
        update-types: ["version-update:semver-minor"]
    groups:
      dependencies:
        patterns:
          - "*"
    target-branch: master