name: "Auto"
on:
  push:
    branches:
      - "master"
  pull_request_target: # every time a PR is closed on master or main
    types:
      - "closed"
    branches:
      - "master"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append to README.md
        run: echo "Hello ${{ github.workflow }}" >> README.md

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Add Hello ${{ github.workflow }} to README.md"

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: master

#      - name: Push changes
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git push
