name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master  # Deploy only when changes are merged to main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Create docs directory and add date.md
        run: |
          mkdir -p docs
          # Write current date into the file
          echo "Current Date: $(date)" > docs/date.md

#      - name: Build the site
#        run: mkdocs build  # Generates the "site/" directory

      - name: Commit and Push Changes
        id: commit-push-release-file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/date.md
          # Use "[skip ci]" to avoid recursive workflow triggers
          git commit -m "Add date.md file [skip ci]" || echo "No changes to commit"

      - name: Push Changes Using Personal Token
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/quyenhnguyen/spring-security-jwt.git
          git push origin master

      - name: Deploy MkDocs
        run: |
          git status
          mkdocs gh-deploy

#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: site  # Uploads the built MkDocs site
#
#      - name: Deploy to GitHub Pages
#        uses: actions/deploy-pages@v4
